spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum
    user: root
    password: caelum
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true

# rabbitmq:
#   host: 192.168.1.9
#   port: 5672
#   username: guest
#   password: guest
