spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alura_gaming
    user: root
    password: caelum
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
  rabbitmq:
    host: 192.168.1.9
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - hystrix.stream
# rabbitmq:
#   host: 192.168.1.9
#   port: 5672
#   username: guest
#   password: guest