spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-api
    user: root
    password: caelum
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
  rabbitmq:
    host: ${services.url.infra}
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - hystrix.stream
services:
  url:
    users: 192.168.0.241
    forum: 192.168.1.13
    courses: 192.168.0.216
    gamefication: 192.168.1.11
    payments: 192.168.1.11
    infra: 192.168.1.9
eureka:
  instance:
    hostname: 192.168.0.241
    instance-id: "${spring.application.name}-${random.uuid}"
  client:
    service-url:
      defaultZone: http://192.168.0.244:8761/eureka